### ISSUE TITLE
動作しません

### ISSUE THREAD

**Issue by YutaUra** [naritotakizawa/django-simple-calendar#12]
git clone から migrate, runserverをしましたが、　localhost:8000/　や他のアドレスにアクセスしても、TypeErrorとなっています。

以下表示されたもののコピー

Request Method: | GET
-- | --
http://localhost:8000/
2.2.2
TypeError
setup() takes 1 positional argument but 2 were given
C:\Users\名前\PycharmProjects\MyDjango\venv\lib\site-packages\django\views\generic\base.py in view, line 65
C:\Users\名前\PycharmProjects\MyDjango\venv\Scripts\python.exe
3.6.6
['C:\\Users\\名前\\PycharmProjects\\MyDjango',  'C:\\Users\\名前\\PycharmProjects\\MyDjango\\venv\\Scripts\\python36.zip',  'C:\\Users\\名前\\Anaconda3\\DLLs',  'C:\\Users\\名前\\Anaconda3\\lib',  'C:\\Users\\名前\\Anaconda3',  'C:\\Users\\名前\\PycharmProjects\\MyDjango\\venv',  'C:\\Users\\名前\\PycharmProjects\\MyDjango\\venv\\lib\\site-packages',  'C:\\Users\\名前\\PycharmProjects\\MyDjango\\venv\\lib\\site-packages\\setuptools-40.8.0-py3.6.egg',  'C:\\Users\\名前\\PycharmProjects\\MyDjango\\venv\\lib\\site-packages\\pip-19.0.3-py3.6.egg']
月, 1 7月 2019 16:00:10 +0900

**Comment by YutaUra** [comment]
Environment:


Request Method: GET
Request URL: http://localhost:8000/

Django Version: 2.2.2
Python Version: 3.6.6
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'app']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback:

File "C:\Users\yuuta\PycharmProjects\MyDjango\venv\lib\site-packages\django\core\handlers\exception.py" in inner
  34.             response = get_response(request)

File "C:\Users\yuuta\PycharmProjects\MyDjango\venv\lib\site-packages\django\core\handlers\base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "C:\Users\yuuta\PycharmProjects\MyDjango\venv\lib\site-packages\django\core\handlers\base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "C:\Users\yuuta\PycharmProjects\MyDjango\venv\lib\site-packages\django\views\generic\base.py" in view
  65.             self.setup(request, *args, **kwargs)

Exception Type: TypeError at /
Exception Value: setup() takes 1 positional argument but 2 were given

**Comment by naritotakizawa** [comment]
Django2.2から、クラスベースビューにsetupというメソッドができており、このアプリケーション内に定義したsetupメソッドと競合してたようです。修正しました。

**Comment by YutaUra** [comment]
早急な対応ありがとうございます！
完璧に修正されております！
いつもブログを参考にDjangoの勉強をさせていただいてます。
ありがとうございました！
